name: behealthy
description: A new Flutter project for promoting healthy eating habits.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slider_drawer: ^2.0.0
  cupertino_icons: ^1.0.2
  animations: ^2.0.0
  provider: ^6.0.0
  flutter_animate: ^1.0.0
  table_calendar: ^3.0.0
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  sqflite: ^2.0.0+4
  path: ^1.8.2
  shared_preferences: ^2.0.0
  path_provider: ^2.0.0
  image_picker: ^0.8.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/beHealthyLogo.png
    - assets/background.jpg
    - assets/tentang/profile.jpg
    - assets/tentang/pict1.png
    - assets/tentang/pict2.jpg
    - assets/tentang/pict3.jpg
    - assets/tentang/pict4.jpg
    - assets/resep/saladbuah.jpg
    - assets/resep/smoothiehijau.jpg
    - assets/resep/oatmealbuah.jpg
    - assets/resep/chiapudding.jpg
    - assets/resep/quinoasalad.jpg
    - assets/resep/supsayur.jpg
    - assets/resep/rotigandum.jpg
    - assets/resep/yogurtgranola.jpg
    - assets/resep/serealbuah.jpg
    - assets/resep/smoothieberry.jpg
    
# Menambahkan fonts jika diperlukan
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
